services:
  postgres_test:
    image: postgres:15
    container_name: test_postgres
    restart: always
    environment:
      POSTGRES_DB: test_ecommerce
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432" #Usamos un puerto diferente para evitar conflictos con la DB principal
    networks:
      - ecommerce_test_network

  mongodb_test:
    image: mongo:6.0
    container_name: test_mongo
    restart: always
    ports:
      - "27018:27017" # Puerto diferente para evitar conflictos
    networks:
      - ecommerce_test_network

networks:
  ecommerce_test_network: