# Ecommerce API

###
# group: Autenticación y Usuario
# @name Registrar Usuario
POST {{base_url}}/api/auth/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123",
  "email": "test@test.cl",
  "role": "admin"
}

###
# group: Autenticación y Usuario
# @name Generar Token (Login)
POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###
# group: Autenticación y Usuario
# @name Lista Usuarios
GET {{base_url}}/api/usuarios
Authorization: Bearer {{auth_token}}

###
# group: Autenticación y Usuario
# @name Obtener usuario por ID
GET {{base_url}}/api/usuarios/1
Authorization: Bearer {{auth_token}}

###
# group: Autenticación y Usuario
# @name Buscar por username
###
# group: Autenticación y Usuario
# @name Actualizar usuario
PUT {{base_url}}/api/usuarios/admin
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "admin",
  "password": "adminupdate",
  "email": "testUpdated@test2.cl",
  "role": "admin"
}

###
# group: Autenticación y Usuario
# @name New Request
###
# group: Productos
# @name Agregar Producto (Admin)
POST {{base_url}}/api/productos
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "codigoProducto": "PROD002",
  "precioUnitario": 2000,
  "stock": 30
}

###
# group: Productos
# @name Listar Productos
GET {{base_url}}/api/productos
Authorization: Bearer {{auth_token}}

###
# group: Productos
# @name Obtener Producto por Código
GET {{base_url}}/api/productos/PROD002
Authorization: Bearer {{auth_token}}

###
# group: Productos
# @name Actualizar un producto
PUT {{base_url}}/api/productos/999

###
# group: Productos
# @name New Request
###
# group: Carrito de Compra
# @name Agregar Producto al Carrito
POST {{base_url}}/api/carrito/usuario123
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "codigoProducto": "PROD001",
  "cantidad": 3
}

###
# group: Carrito de Compra
# @name Obtener Carrito de Usuario
GET {{base_url}}/api/carrito/usuario123
Authorization: Bearer {{auth_token}}

###
# group: Carrito de Compra
# @name Eliminar Producto del Carrito
DELETE {{base_url}}/api/carrito/usuario123/PROD001
Authorization: Bearer {{auth_token}}

###
# group: Carrito de Compra
# @name Vaciar Carrito de Usuario
DELETE {{base_url}}/api/carrito/usuario123
Authorization: Bearer {{auth_token}}

###
# group: Compras
# @name Realizar Compra
POST {{base_url}}/api/compra/usuario123
Authorization: Bearer {{auth_token}}